version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Resume_Thomas_Hatting.pdf
    - My_Reading_List.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
